// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaiDuongScada.Infrastructure;

#nullable disable

namespace ThaiDuongScada.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230525090419_UpdateShiftTime")]
    partial class UpdateShiftTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.DeviceAggregate.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<bool>("Manipular")
                        .HasColumnType("bit");

                    b.Property<double>("MaxPressure")
                        .HasColumnType("float");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<double>("MinPressure")
                        .HasColumnType("float");

                    b.Property<int>("MinTemperature")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.DeviceMouldAggregate.DeviceMould", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MouldSlot")
                        .HasColumnType("int");

                    b.Property<string>("MouldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PreviousShotCount")
                        .HasColumnType("int");

                    b.Property<int>("ShiftDuration")
                        .HasColumnType("int");

                    b.HasKey("DeviceId", "MouldSlot");

                    b.HasIndex("MouldId");

                    b.ToTable("DeviceMoulds");
                });

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.MouldAggregate.Mould", b =>
                {
                    b.Property<string>("MouldId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cav")
                        .HasColumnType("int");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardOutput")
                        .HasColumnType("int");

                    b.HasKey("MouldId");

                    b.ToTable("Moulds");
                });

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.ShiftReportAggregate.ShiftReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectCount")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MouldSlot")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<double>("ProductPercentage")
                        .HasColumnType("float");

                    b.Property<int>("ShiftDuration")
                        .HasColumnType("int");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ShiftReports");
                });

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.DeviceMouldAggregate.DeviceMould", b =>
                {
                    b.HasOne("ThaiDuongScada.Domain.AggregateModels.DeviceAggregate.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThaiDuongScada.Domain.AggregateModels.MouldAggregate.Mould", "Mould")
                        .WithMany()
                        .HasForeignKey("MouldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Mould");
                });

            modelBuilder.Entity("ThaiDuongScada.Domain.AggregateModels.ShiftReportAggregate.ShiftReport", b =>
                {
                    b.HasOne("ThaiDuongScada.Domain.AggregateModels.DeviceAggregate.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ThaiDuongScada.Domain.AggregateModels.ShiftReportAggregate.Shot", "Shots", b1 =>
                        {
                            b1.Property<int>("ShiftReportId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("InjectionCycle")
                                .HasColumnType("float");

                            b1.Property<double>("InjectionTime")
                                .HasColumnType("float");

                            b1.Property<DateTime>("TimeStamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("ShiftReportId", "Id");

                            b1.ToTable("Shot");

                            b1.WithOwner()
                                .HasForeignKey("ShiftReportId");
                        });

                    b.Navigation("Device");

                    b.Navigation("Shots");
                });
#pragma warning restore 612, 618
        }
    }
}
